export default {
  light: {
    text: '#000',
    background: '#fff',
    reverseBackground: '#000',
    sectionColor: '#fff',
    sectionSupportColor: 'rgb(230, 230, 230)',
  },
  dark: {
    text: '#fff',
    background: '#000',
    reverseBackground: '#fff',
    sectionColor: 'rgb(43, 43, 43)',
    sectionSupportColor: 'rgb(90, 90, 90)',
  },
  roulette: ['#50a5e5', '#e94b8b'],
  ACTIVE: '#0874cb',
  TRANSPARENT: 'transparent',
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  GRAY: '#EEEEEE',
  RED: '#b30505',
  white: (opacity = 1): string => `rgba(255, 255, 255, ${opacity})`,
  black: (opacity = 1): string => `rgba(0, 0, 0, ${opacity})`,
  rgb: (r = 0, g = 0, b = 0): string => `rgb(${r}, ${g}, ${b})`,
  rgba: (r = 0, g = 0, b = 0, a = 0): string => `rgba(${r}, ${g}, ${b}, ${a})`,
}
